### ISSUE TITLE
[Bug] : update is-svg dep in postcss-svgo for CVE-2021-28092

### ISSUE THREAD

**Issue by kemarsh** [cssnano/cssnano#1019]
`cssnano@4.1.10` depends on a version of `is-svg` that is vulnerable to:

https://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2021-28092

```
  cssnano@4.1.10
      └─┬ cssnano-preset-default@4.0.7
        └─┬ postcss-svgo@4.0.2
          └── is-svg@3.0.0
```

The package.json https://github.com/cssnano/cssnano/blob/4.x.x/packages/postcss-svgo/package.json has been updated to contain `"is-svg": "^4.1.0"` but we're still getting `"is-svg": "^3.0.0"` from what's published to npm.

Could `postcss-svgo@4.0.2` be updated to depend on `is-svg@4.2.2`?

**Comment by ludofischer** [comment]
It is fixed in postcss-svgo@5.0.0-rc.2

**Comment by SymbioticKilla** [comment]
It is also fixed in 4.x.x branch but it is need to be released: https://github.com/cssnano/cssnano/issues/1018

**Comment by kemarsh** [comment]
Full dependency tree below -  I'm pulling in via `cssnano@4.1.10` which is still tagged as the `latest` release so I can't choose to bump `postcss-svgo` version.
```
┬ react-scripts@4.0.3
  └─┬ optimize-css-assets-webpack-plugin@5.0.4
    └─┬ cssnano@4.1.10
      └─┬ cssnano-preset-default@4.0.7
        └─┬ postcss-svgo@4.0.2
          └── is-svg@3.0.0
```
Would appreciate confirmation that 4.x.x stream will or won't be fixed.

**Comment by ludofischer** [comment]
Speaking for myself, I won't likely publish a new 4.x.x release, simply because I don't know what the state of that branch is right now, so I don't know whether publishing from that will result in working software.
From what I understand reading the CVE, the issue is that the SVG parser can get stuck reading some inputs.
I believe the vulnerability is only serious if you process user input with cssnano, otherwise I do not see how these problematic strings could hit the parser. Even then, in the case of a build tool, the worse that could happen is that your build would hang. Even if someone tried to mount a denial of service attack on your CI server, they would need to be able to inject their own input in the build pipeline, so at that point I do not believe they would even need this specific vulnerability to do harm.
