### ISSUE TITLE
[Bug] : @media feature value is dropped incorrectly

### ISSUE THREAD

**Issue by alan-agius4** [cssnano/cssnano#1105]
**Describe the bug**
The `@media` query feature value `all` is dropped incorrectly.

**To Reproduce**
Providing the following input:
```css
@media all { p{ display: none; } }
```

The following output is generated
```css
@media{p{display: none;}}
```

**Expected behavior**
`@media all` is retained as the outputted CSS is invalid

**Desktop (please complete the following information):**
- CSSNANO Version [e.g. 22] 5.0.2
- Plugins/presets versions default present set.
- Add the output of `npx envinfo && npm ls cssnano` here
```

  System:
    OS: macOS 11.2.3
    CPU: (16) x64 Intel(R) Core(TM) i9-9880H CPU @ 2.30GHz
    Memory: 22.31 GB / 64.00 GB
    Shell: 5.8 - /bin/zsh
  Binaries:
    Node: 12.20.2 - ~/.nvm/versions/node/v12.20.2/bin/node
    Yarn: 1.22.10 - ~/.nvm/versions/node/v12.20.2/bin/yarn
    npm: 6.14.13 - ~/.nvm/versions/node/v12.20.2/bin/npm
  Managers:
    Homebrew: 2.4.6 - /usr/local/bin/brew
    pip3: 20.1 - /usr/local/bin/pip3
    RubyGems: 3.0.3 - /usr/bin/gem
  Utilities:
    Make: 3.81 - /usr/bin/make
    GCC: 4.2.1 - /usr/bin/gcc
    Git: 2.26.2 - /usr/local/bin/git
    Clang: 11.0.3 - /usr/bin/clang
  Servers:
    Apache: 2.4.46 - /usr/sbin/apachectl
  IDEs:
    Nano: 2.0.6 - /usr/bin/nano
    VSCode: 1.56.1 - /usr/local/bin/code
    Vim: 8.2 - /usr/bin/vim
    Xcode: /undefined - /usr/bin/xcodebuild
  Languages:
    Bash: 3.2.57 - /bin/bash
    Perl: 5.28.2 - /usr/bin/perl
    PHP: 7.3.24 - /usr/bin/php
    Python: 2.7.16 - /usr/bin/python
    Python3: 3.7.3 - /usr/bin/python3
    Ruby: 2.6.3 - /usr/bin/ruby
  Databases:
    SQLite: 3.32.3 - /usr/bin/sqlite3
  Browsers:
    Chrome: 90.0.4430.212
    Firefox: 78.9.0
    Safari: 14.0.3

quiz-app@0.0.0 /cli-reproductions/quiz-app
└─┬ @angular-devkit/build-angular@12.0.0
  └── cssnano@5.0.2 
```

**Additional context**

**Comment by ludofischer** [comment]
I cannot reproduce this with cssnano 5.0.6. Are additional rules required to trigger this?

**Comment by sigveio** [comment]
> (...)
> quiz-app@0.0.0 /cli-reproductions/quiz-app
> └─┬ @angular-devkit/build-angular@12.0.0
>   └── cssnano@5.0.2 

I was able to recreate the behaviour by creating a fresh Angular app using their CLI tool, which used cssnano 5.0.6, adding the provided input to `src/styles.css` and running `npm run build`

But I would argue that...

> Expected behavior
> `@media all` is retained as the outputted CSS is invalid

Is false. Because these are equivalent:

```
@media all { … }
@media { … }
```
(ref: https://www.w3.org/TR/mediaqueries-5/#media-query-list)

When no media type is provided, it defaults to all. Hence it is a shorter/minified version.

**Comment by sigveio** [comment]
I investigated this a bit further since I was curious about why the `all` was removed with Angular's implementation and not when I initially fired up a simple test with standalone webpack and cssnano to reproduce.

Angular uses `css-minimizer-webpack-plugin` which in turn uses `cssnano` with `cssnano-preset-simple`. This preset includes the plugin `postcss-minify-params` which takes care of cleaning up media queries.

It's done by this part:

https://github.com/cssnano/cssnano/blob/ef098b12b71bc27004572239c1200f7625008dde/packages/postcss-minify-params/src/index.js#L60-L69

And `legacy` is passed in as a param from here:

https://github.com/cssnano/cssnano/blob/ef098b12b71bc27004572239c1200f7625008dde/packages/postcss-minify-params/src/index.js#L107

Which stems from this check:

https://github.com/cssnano/cssnano/blob/ef098b12b71bc27004572239c1200f7625008dde/packages/postcss-minify-params/src/index.js#L92-L94

Which takes into account that IE 10 and 11 didn't play well with removal of `all`

This check is ran on the list of browsers defined as supported in `.browserlistrc` - and since Angular 12.x only supports IE by opt in (so not by default) the `postcss-minify-params` plugin removes `all` as intended when not needed.

**Comment by blankse** [comment]
We have the problem that the PDFReactor (https://www.pdfreactor.com/) doesn't accept `@media {}`
The PDFReactor support says this is not a valid CSS we should change it. We must create a .browerlistrc with IE to generate the correct CSS. We generate the CSS with `@media print {}` for the Website and with `@media all {}` for Web2Print with LESS/SASS variables.

So my question:
Why not remove completely `@media all {}` This should work in all browser, right?
