### ISSUE TITLE
[Bug] : High vulnerability ReDoS in normalize-url in cssnano 4

### ISSUE THREAD

**Issue by corradin** [cssnano/cssnano#1141]
There is a Regular Expression Denial of Service (ReDoS) vulnerability in the normalize-url dependency.

The vulnerability has been fixed in normalize-url versions: `6.0.1`, `5.3.1` and `4.5.1`

The latest version of postcss-normalize-url (`5.0.1`) still uses the unfixed version of normalize-url (`4.5.0`). This vulnerability can be fixed by including version `4.5.1`, `5.3.1` or `6.0.1`, see: https://github.com/sindresorhus/normalize-url/releases/tag/v6.0.1

**Comment by alexander-akait** [comment]
Please update `cssnano` to v5

**Comment by ludofischer** [comment]
Hi, thank you for the reminder. You do not need to wait for cssnano to update the dependency , `postcss-normalize-url` accepts all minor and patch updates of `normalize-url` 4 (because of the caret in front of the version number):
https://github.com/cssnano/cssnano/blob/36cef9255ec532a4a47f1d776c1a792bae64c1b4/packages/postcss-normalize-url/package.json#L27
so you can run `npm update normalize-url` on your side to update.

**Comment by corradin** [comment]
Thanks for the responses. I am depending on version `4.1.11` of cssnano (through another package) and that version includes the following: ` "postcss-normalize-url": "^4.0.1"`
Is it an option to update this to `4.5.1` or `^4.5.0`?

**Comment by corradin** [comment]
Thanks for the responses. I am depending on version `4.1.11` of cssnano (through another package) and that version includes the following: ` "normalize-url": "^3.0.0",`
Is it an option to update this to `4.5.1` or `^4.5.0`?

**Comment by alexander-akait** [comment]
Why? Please read how semver works

**Comment by corradin** [comment]
@alexander-akait Sorry, I think you misunderstood my question.
I am depending on version `4.1.11` of cssnano in which cssnano includes version `3.0.x` of normalize-url.
Instead of including version `3.0.x` would it be possible to include `^4.5.0`?

**Comment by ludofischer** [comment]
> @alexander-akait Sorry, I think you misunderstood my question.
> I am depending on version `4.1.11` of cssnano in which cssnano includes version `3.0.x` of normalize-url.
> Instead of including version `3.0.x` would it be possible to include `^4.5.0`?

I think it's unlikely we'll update cssnano 4. version 4 is not really maintained any more. Besides, as far as I can see,  the attacker would need to inject maliciously crafted URLs in the CSS you pass to cssnano. I you use `normalize-url` as part of your build it is going to run on trusted input (your own CSS), so the issue is limited.
