### ISSUE TITLE
[Feature Request] Replace html2plaintext dependency in postcss-reduce-initial

### ISSUE THREAD

**Issue by sigveio** [cssnano/cssnano#1159]
## Is your feature request related to a problem? Please describe.

I noticed that the acquire tool in `postcss-reduce-initial` which builds the from/to JSON files depends on the package `html2plaintext` which has a transitive dependency of a vulnerable `css-what` version.

So I headed over to their [repo](https://github.com/kurttheviking/html2plaintext) - and it's not been updated for 3 years.
From what I can see, it doesn't appear to be maintained.

## Describe the solution you'd like

Since it's just a helper tool for generating files for the package I suppose it's not a big issue, but for the sake of prudence I would propose replacing `html2plaintext` with [html-to-text](https://www.npmjs.com/package/html-to-text), which appears to be much more frequently used and actively maintained.

## Are you willing to work on this ?

Yes - happy to submit a PR if you agree 👍

**Comment by alexander-akait** [comment]
Yep PR welcome

**Comment by sigveio** [comment]
Aight, coming up :-)

Should I also regenerate `fromInitial.json` and `toInitial.json` while I'm at it? 

There's various additions and a few deletions/changes since it was last generated. (All tests passes with them)

**Comment by ludofischer** [comment]
I think you've got to include the changes to `fromInitial.json` and `toInitial.json`, else we cannot check if the result is still correct. I have never looked into `reduce-initial` in detail, but from a cursory look I am not surprised the tests pass, since the tests check the output against the `json` files. I think we need to inspect the files by hand and see if the changes make sense.

**Comment by sigveio** [comment]
Yeah, you are right about that. So if you don't mind, I would like to refactor the acquire script a bit more heavily to make it testable - and pair it with a test suite of its own. Then generation of those files could perhaps also be automated at some point - so they are always kept up to date. Having test coverage would also make it easier for some future contributor to maintain/refactor with confidence.

**Comment by ludofischer** [comment]
While you're at it, you could also replace the `got` dependency as it brings a lot of transitive dependencies for no benefit to us since we do not need an isomorphic HTTP client. I don't mind refactoring and unit tests, although unit tests can't protect from the source JSON file changing format, which might be the main risk here.

**Comment by sigveio** [comment]
Good point on `got`; will do. :-)

Regarding the source JSON changing format; perhaps snapshotting the two json files could be an extra guard? It would offer some protection against big/obvious unexpected changes by requiring a review of the failed test and snapshot update. 

With that and the general test suite, the file generation could then still be automated. With the benefit of catching updates fairly quickly, rather than whenever someone remembers to check it.

I don't imagine the source JSON is updated so often that it would become bothersome - but if so it could always be reverted.
