### ISSUE TITLE
[Bug]: https://cssnano.co/playground/ fails to minify input

### ISSUE THREAD

**Issue by DenyVeyten** [cssnano/cssnano#1311]
### Describe the bug

Default and Advanced presets:
![image](https://user-images.githubusercontent.com/11442834/151367322-449fe6b1-f26f-4dc0-b36c-fc24d1129fe8.png)

### Expected behaviour

Playground minifies input successfully

### Steps to reproduce

1. Open https://cssnano.co/playground/
2. Press "Play" button

### Version

5.0.16?

### Preset

default

### Environment

```shell
Google Chrome 97.0.4692.71
```

### Package details

```shell
Whatever playground uses
```

**Comment by ludofischer** [comment]
Hello, thank you for your report? Do you find the playground useful? I'm asking because I wonder if it would not be better to shut down the playground. It is not the first time the playground breaks because some cssnano dependencies are not designed to run in a browser, so we have to use a lot of polyfills, and sometimes ask the upstream maintainers to change their package just so it runs in the playground. Alternatively we could make a different cssnano build for the browser, but it would be a bit misleading because then it would not necessarily produce the same output as when you run it locally.

**Comment by DenyVeyten** [comment]
@ludofischer Hi, thanks for a quick fix! Yes, it's useful for legacy projects + when someone wants to see a demo or experiment with something.
You can check/put analytics for the playground usage. I'm pretty sure lots of people still using this.
Just have checked "css minify online" in google trends, some data is still there, so looks like it still has some popularity.
