### ISSUE TITLE
[Feature Request]: postcss-reduce-idents should reduce grid-column area names

### ISSUE THREAD

**Issue by jordydhoker** [cssnano/cssnano#1362]
### What should be improved?

Currently postcss-reduce-idents reduces the names of grid area's in the grid-area property. Area names can also be used in the grid-column and grid-row properties as they are shorthands for the same properties grid-area is a shorthand for. These properties should also be checked when reducing area names.

### Describe the solution you would like

Reduce grid area names in the grid-column and grid-row properties.

### Additional context

This is purely an enhancement, can't really break anything.

### Are you willing to work on this?

- [X] Yes, I would like to help

**Comment by ludofischer** [comment]
Sure, I can review your PR if you submit one. There's a few remarks that come to mind:
1. There could be more hidden bugs in reduce-idents than in other presets because it is used a lot less. `reduce-idents` as it is part of the `advanced` preset, which is not applied by cssnano by default. `reduce-idents` has less than 1 million downloads per week, while cssnano has over ten millions.
2. From my experience, we tend to forget about corner cases such as issues with the cascade or rarely used properties or cross-browser compatibility. For example, see https://github.com/cssnano/cssnano/issues/656 where we forgot about `border-image` when merging border properties. or this issue where we break the cascade https://github.com/cssnano/cssnano/issues/864 Renaming does seem more predictable, of course it's going to break if a different stylesheet references the name, but that's why the transform is part of the advanced preset.

**Comment by jordydhoker** [comment]
I submitted a PR, hope it helps!
https://github.com/cssnano/cssnano/pull/1366

**Comment by jordydhoker** [comment]
Updated the PR to include better tests and support for *-start and *-end properties as they support grid area names as well

**Comment by ludofischer** [comment]
Fixed in https://github.com/cssnano/cssnano/commit/6c2a2a6049a6079ceb3245e97d38ff36afcb2c30
