### ISSUE TITLE
Inline eslint configuration?

### ISSUE THREAD

**Issue by jordrake** [cssnano/cssnano#635]
I noticed there are some inconsistencies across the packages (e.g. single and double quotes) and saw that this uses an external but specific eslint config located at https://github.com/ben-eb/eslint-config-cssnano. 

I am assuming at one point this was because the packages used to be spread out across various repositories. Now this is no longer the case (I believe?) could we bring the eslint configuration inline either as a top-level .eslintrc or a packages/eslint-config-cssnano to make it easier to update. 

Or just use a shared one.

**Comment by evilebottnawi** [comment]
@jordrake Yes, we need do it, also we should use `prettier` https://github.com/prettier/prettier for code style. I think we can avoid creating new package because we in monorepo. Feel free to send a PR.

Also will be great to switch from `ava` to `jest` with snapshot testing, he is faster and snapshot allow writing test very fast and very conveniently. Ava also have snahpshot, but the last time when i use their they were very unstable.

**Comment by jordrake** [comment]
You'll get no argument from me on any of those fronts.

The conversion from jest to ava might be slightly painful as the tests rely a lot of ava's macro functionality but we could add a utility function which has the same signature or do something clever with codemods.

**Comment by evilebottnawi** [comment]
@jordrake yep, so migration from `ava` to `jest` is not high priority. We have other high priority bugs https://github.com/cssnano/cssnano/issues/411 https://github.com/cssnano/cssnano/issues/458 https://github.com/cssnano/cssnano/issues/535 (require more work). Any help welcome.

**Comment by andyjansson** [comment]
> #411 #458 

These two I'll fix. Declaration sorting I haven't started on.
