### ISSUE TITLE
postcss-reduce-initial 4.0.2 - Template:CSSData by Mozilla Contributors is licensed under CC-BY-SA 2.5.

### ISSUE THREAD

**Issue by luisapace** [cssnano/cssnano#646]
Hi, my team would like to use the package **_postcss-reduce-initial 4.0.2_** and to approve that I've to verify all its licenses. 
In the readme I see written:  "Template:CSSData by Mozilla Contributors is licensed under CC-BY-SA 2.5", but I cannot find any template in that package. 
Could you please confirm me if there any CC-BY-SA 2.5 piece of code in **_postcss-reduce-initial 4.0.2_**? in this case where is that piece of code?

Thanks a lot.

**Comment by evilebottnawi** [comment]
@luisapace oh, it is bug, we use MIT, feel free to send PR with change this https://github.com/cssnano/cssnano/tree/master/packages/postcss-ordered-values#license

**Comment by luisapace** [comment]
Thanks for you quick confirmation!

**Comment by andyjansson** [comment]
What are you asking?

**Comment by evilebottnawi** [comment]
@andyjansson It is compatibility with OSS projects and commercial use? Should/Can we change license?

**Comment by andyjansson** [comment]
It's not our license, it's Mozilla's. And yes, it allows commercial use. Just click the link for the license: 

> Adapt — remix, transform, and build upon the material for any purpose, **even commercially.**

**Comment by luisapace** [comment]
Hi, I've seen your last comments, and I think I've to redo the initial question:
In the readme I see written: "Template:CSSData by Mozilla Contributors is licensed under CC-BY-SA 2.5", but I cannot find any template in that package.
Could you please confirm me if there any CC-BY-SA 2.5 piece of code in postcss-reduce-initial 4.0.2? in this case where is that piece of code?
Thanks.

**Comment by luisapace** [comment]
thanks

**Comment by onewaypub** [comment]
Hi @alexander-akait 

one question: CC-BY-SA 2.5 is a Copyleft license (similar to the GPL). Hence anything that is a "Derivative Work" needs to be licensed under CC-BY-SA 2.5 as well. Is there a chance to replace the template by something that is MIT licensed? Otherwise: could you indicate that the software is under CC-BY-SA 2.5?

**Comment by ludofischer** [comment]
@onewaypub I would not call it a template; it's a list of the initial value for all CSS properties: https://github.com/cssnano/cssnano/blob/master/packages/postcss-reduce-initial/data/fromInitial.json The issue I see is that if we 'replaced' it(for example by looking through the spec ourselves), it would not be possible to tell, because the list would end up identical.

**Comment by ludofischer** [comment]
Mozilla changed the license in 2018 to Creative Commons 0 https://github.com/mdn/data/blob/main/LICENSE  and as far as I can tell there is no Creative Commons 2.5 content in postcss-reduce-initial. I've opened a PR to update the README https://github.com/cssnano/cssnano/pull/1335
