### ISSUE TITLE
'cssnano-preset-default' using deprecated 'postcss-colormin' dependency

### ISSUE THREAD

**Issue by silkfire** [cssnano/cssnano#916]
Is it correct that `cssnano-preset-default` should use the deprecated `postcss-colormin` package?

`postcss-colormin` uses an older version of `browserslist` which makes npm complain about it.

**Comment by anikethsaha** [comment]
in master, default preset is using the latest version (I guess) of `postcss-colormin`

About the old browserlist, It will be fixed in next version as I think it has been updated in master

**Comment by silkfire** [comment]
Thanks for the update. When is the next release planned?

**Comment by anikethsaha** [comment]
> Thanks for the update. When is the next release planned?

soon

**Comment by karlhorky** [comment]
Came here because of the security vulnerabilities on `dot-prop`: https://github.com/advisories/GHSA-ff7x-qrg7-qggm

![Screen Shot 2020-07-31 at 10 42 42](https://user-images.githubusercontent.com/1935696/89017566-cbcc5d80-d31a-11ea-8d81-16b89d89fb2b.png)

![Screen Shot 2020-07-31 at 10 43 10](https://user-images.githubusercontent.com/1935696/89017579-cf5fe480-d31a-11ea-8c98-db60e20bf91d.png)

**Comment by karlhorky** [comment]
Very confusing and time-consuming because the dependencies in the current published version of `cssnano-preset-default` do not match those on GitHub:

**Published `cssnano-preset-default@4.0.7`**

<img width="542" alt="Screen Shot 2020-07-31 at 10 44 47" src="https://user-images.githubusercontent.com/1935696/89017663-f6b6b180-d31a-11ea-8975-a2f2a0fbd818.png">

**GitHub `cssnano-preset-default@4.0.7`**

<img width="669" alt="Screen Shot 2020-07-31 at 10 46 55" src="https://user-images.githubusercontent.com/1935696/89017813-2fef2180-d31b-11ea-9760-1af0ac31ec1d.png">

**Comment by karlhorky** [comment]
@anikethsaha or should I open a new issue about the security vulnerability?

**Comment by anikethsaha** [comment]
You are checking the dependencies of the master branch which is quite up to date I guess,

`cssnano-preset-default@4.0.7` was published a year ago and the dependencies in the master branch were updated 5 months ago. 

`postcss-colormin` is in latest version in `cssnano-preset-default`. As mentioned it will be fixed when releasing the next version of `cssnano-preset-default`

in the meantime, you can use `cssnano-preset-default@nightly` which is up to date with this `master`

**Comment by karlhorky** [comment]
Ok, when can a new version be published?

I've opened this new issue to track the security vulnerabilities in `dot-prop`: https://github.com/cssnano/cssnano/issues/931

**Comment by evilebottnawi** [comment]
Fixed in the master
